### PR TITLE
Fix: Default version

### LINKED ISSUE #77: Builderator can't bring local VMs up if there aren't version tags in the current repository
If you start a brand new project with Builderator, there wan't be version tags in the local repository. This causes `build local` to fail with the error message

``` text
gems/builderator-1.1.4/lib/builderator/tasks/version.rb:27:in `current': undefined method `ref' for nil:NilClass (NoMethodError)
```

The [check for the current version](https://github.com/rapid7/builderator/blob/master/lib/builderator/control/version.rb#L34) should default to "0.0.1" if a version number can't be resolved from source control.

### PR DESCRIPTION
**Pull request by fmitchell-r7**
This fixes #77. Builderator will now fall back to reading a VERSION file in the repository (if one exists) when the SCM provider doesn't have any tags. This allows you to do local development with Builderator before committing and releases to your repository.

### CODE REVIEW

**Comment by athompson-r7** [comment]
Unless I misunderstand things, I don't think this fixes the issue.  You will still need an initial tag to release on a CI system.

File: lib/builderator/control/version.rb [hunk 1]
```diff
@@ -32,6 +32,12 @@ class Version
       class << self
         def current
           @current ||= SCM.tags.last
+
+          if @current.nil? && Util.relative_path('VERSION').exist?
```
Comment (erran-r7) [inline lib/builderator/control/version.rb]: Should we leave this? `@current ||= ...` will already perform this check in a way. If `@current` is non-nil it will not re-assign it.

**Comment by erran-r7** [comment]
> I don't think this fixes the issue

@fmitchell-r7 I agree with @athompson-r7, it looks like if the `VERSION` file is not present then this will still 💣 with the same exception.

File: lib/builderator/control/version.rb [hunk 2]
```diff
@@ -32,6 +32,12 @@ class Version
...
+            @current ||= Version.from_string(Util.relative_path('VERSION').read)
+          end
+
+          @current
```
Comment (erran-r7) [inline lib/builderator/control/version.rb:44]: @fmitchell-r7 @athompson-r7 How about the following to provide a clear error message with a _workaround_ to this issue?

``` ruby
def current
  @current ||= SCM.tags.last
  @current ||= Version.from_string(Util.relative_path('VERSION').read) if @current.nil? && Util.relative_path('VERSION').exist?
  return @current if @current

  raise 'No current version could be detected. Create a VERSION file to release with no version SCM tags present.'
end
```

Alternatively in the `else` we default to some other version number.

Comment (fmitchell-r7) [inline lib/builderator/control/version.rb:44]: @erran-r7 @athompson-r7 I like the idea of an error message.

I avoided picking a default version number because I'm not sure _what_ to pick. I've seen projects use 0.0.1, 0.1.0, and 1.0.0, all with valid reasons for why that's the right default.

File: lib/builderator/control/version.rb [hunk 3]
```diff
@@ -32,6 +32,16 @@ class Version
       class << self
         def current
           @current ||= SCM.tags.last
+
+          if @current.nil? && Util.relative_path('VERSION').exist?
+            @current = Version.from_string(Util.relative_path('VERSION').read)
+          end
+
+          if @current.nil?
+            fail 'No current version found! Create a VERSION file or set a version tag in your SCM.'
```
Comment (erran-r7) [inline lib/builderator/control/version.rb:41]: @fmitchell-r7 Don't we normally set RuboCop to use `raise` over `fail` (as much as I prefer `fail` myself)? 😉

File: spec/version_spec.rb [hunk 4]
```diff
@@ -33,6 +46,33 @@ def self.supported?
...
+          SCM.register(Test)
+        end
+
+        context 'current' do
+          it 'provides an error message if no version is found' do
+            version_file = Util.relative_path('VERSION')
+            version_file.delete if version_file.exist?
+
+            expect(SCM.tags.last).to be_nil
+            expect { Version.current }.to raise_error RuntimeError
```
Comment (erran-r7) [inline spec/version_spec.rb:66]: I'm pretty sure `expect { Version.current }.to raise_error` is sufficient, unless we really care about the error type.

File: spec/version_spec.rb [hunk 5]
```diff
@@ -33,6 +46,33 @@ def self.supported?
...
+          end
+
+          it 'falls back to VERSION file if no tags are found' do
+            Util.relative_path('VERSION').write('1.2.3')
```
Comment (erran-r7) [inline spec/version_spec.rb:70]: @fmitchell-r7 shouldn't we clean up the file here?

We could also stub `Util.relative_path('VERSION')` to return a mock file which prevents writing to disk.

File: lib/builderator/control/version.rb (hunk 3 above)
Comment (fmitchell-r7) [inline lib/builderator/control/version.rb:41]: I used `fail` instead of `raise` because [existing code uses `fail`](https://github.com/rapid7/builderator/blob/fix-default-version/lib/builderator/control/version/scm.rb#L76-L77) and I wanted to keep it consistent.

File: spec/version_spec.rb (hunk 4 above)
Comment (fmitchell-r7) [inline spec/version_spec.rb:66]: I followed the [format of other `Version` tests](https://github.com/rapid7/builderator/blob/fix-default-version/spec/version_spec.rb#L168) that explicitly check for an error type.

File: spec/version_spec.rb (hunk 5 above)
Comment (fmitchell-r7) [inline spec/version_spec.rb:70]: We've got [code in place already](https://github.com/rapid7/builderator/blob/fix-default-version/spec/spec_helper.rb#L8-L16) for `Util.relative_path` in tests. I'll see if I can extend it to skip writing the VERSION file to disk.

File: spec/version_spec.rb (hunk 4 above)
Comment (erran-r7) [inline spec/version_spec.rb:66]: @fmitchell-r7 I'm happy with consistency. 😄

File: spec/version_spec.rb (hunk 5 above)
Comment (erran-r7) [inline spec/version_spec.rb:70]: @fmitchell-r7 Sounds good, minor anyways. I'm happy if we're being consistent here. No reason to slow down this PR. :shipit: We can (I'll play around when I have free time) refactor to use mocks later.
